modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/jshipley/Bushcraft/issues"
license = "MIT"

[[mods]]
modId = "bushcraft"
version = "${version}"
displayName = "Bushcraft"
authors = "jship"
description = '''
Bushcraft is a low-tech tech mod that can help you survive and gather resources, especially in the early game.
'''
logoFile = "assets/bushcraft/icon.png"

[[dependencies.bushcraft]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bushcraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bushcraft]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bushcraft]]
modId = "geckolib"
type = "required"
versionRange = "[4.7.5,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bushcraft.mixins.json"
